# Plane API Basic Configuration
domain: "https://projects.camio.acep.uaf.edu"
api_version: "v1"
workspace_slug: "cyberinfrastructure"
cred_filename: "plane.cred"

# Full Plane Report
start_date: "2025-10-01"
end_date: "2025-12-22"

# todo: Include output types/locations...

# Project Based Report
project_id: ""

# Task Status Configuration
task_status:
  - "Done"
  - "Ready for Review"
  - "Pending"
  - "Completed"
  - "Cancelled"
  - "Blocked"
  - "Backlog"
  - "Todo"